version: '3.7'

services:

  web:
    build: ./app
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web
    depends_on:
      - web-db

  web-db:
    image: postgres:12-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=web
